services:
  pgvector:
    container_name: pgvector
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    labels:
      - "org.springframework.boot.service-connection=postgres"
    volumes:
      - ./volume-data/postgres:/var/lib/postgresql/data
